- name: Konfiguracja serwera produkcyjnego AWS
  hosts: all
  become: yes
  gather_facts: no 

  tasks:
    - name: Instalacja python i ufw (Metoda bezpośrednia)
      raw: |
        apt-get update && \
        apt-get install -y python3-minimal ufw
      register: raw_result

    - name: Konfiguracja Firewall
      shell: |
        ufw allow 22/tcp
        ufw allow 80/tcp
        echo "y" | ufw enable